### ISSUE TITLE
parts of the horizontal stabilizer and fairings are black

### ISSUE THREAD

**Issue by gilbertohasnofb** [c172p-team/c172p-detailed#135]
The sides of the horizontal stabilizer are black both in our plane and also in the old c172p. We are just importing the bump map effect from the old c172p directory, and the problem seems to be in this effect. EDIT: This happens when the slider in Shaders->Model is set to anything except "low".

**Comment by Juanvvc** [comment]
This happens with the slider is set to any step *except* "low" :) It the shader is set to low, the bump map is not loaded and all surfaces are ok. At least, in my PC.

**Comment by gilbertohasnofb** [comment]
I confirm that.

**Comment by wlbragg** [comment]
The back of the fairings are black also.

**Comment by Juanvvc** [comment]
wlbragg, I don't understand your comment. I believe it is because these surfaces were mapped into a line, not an area. Mapping into a line worked in the past but it seems the new ubershader (updated again today in FGDATA) needs all UV surfaces to have a non-zero area. Initial tests fixed the issue by remapping the dark faces into areas and not lines, but it will involve identifying and remapping again all black faces one by one. I will try to remap them in a way that won't make necessary redoing all liveries.

**Comment by gilbertohasnofb** [comment]
These black areas are not related to our textures. I tested it by applying full red textures to the fuselage, wing and tail and the black places are still present. I don't think they have anything to do with our tail.png.

**Comment by Juanvvc** [comment]
I'm fixing this by remapping borders like this:

![snapshot1](https://cloud.githubusercontent.com/assets/684228/7434022/1e787dec-f037-11e4-90ab-f770465e01bc.png)

Before that, borders where mapped as a line since the elevator was projected from the top view. It seems to me the new ubershader do not like faces to be mapped into a line. I'm projecting into these small areas of the texture. These areas were not used until now, but they seem ok in all current liveries.

But this is caused by the new ubershader, so we must warn the author. It is going to affect to many other aircraft for sure.

**Comment by wlbragg** [comment]
Way over my head.
 You are talking about the texture map? Related to the tail.png but only by the map for its placement?

Can you post the original map for comparison so I can understand better what you talking about?

 I trust you have a handle on it.

**Comment by Juanvvc** [comment]
![snapshot2](https://cloud.githubusercontent.com/assets/684228/7435007/e96a6ecc-f03f-11e4-85e7-c74f1aeb3d0f.png)

The border was uv-mapped to the bottom line.

You map surfaces by projecting them. The border of the elevator is orthogonal to the ground. If you map the surfaces from the top view, the border is going to be uv-mapped as a line. This is ok for a texture: the face is going to be shown as a line of pixels repeated from top to bottom. But mapping into a line seems not ok for the current ubershader. It is logical: if the uv-map of a face is a line, the ubershader cannot compute the normal vector and then the normal shader (the bump map) is not going to work. I don't know if in this case in the past the ubershader was not applied or what, but currently it seems the shader fails and the face is drawn as black.

This is my understating of the issue and I may be wrong. It is already fixed in my PC by mapping all dark faces I identified to areas and not lines. I have not committed this yet because I'm also addressing other uv-map related issues like #138

**Comment by Juanvvc** [comment]
Ok, done an fixed for most faces, but there are two small places where the fix didn't work very well and I need your help: the very front and the very back of the aircraft. We have textures for the left and right side, but not the front or the back.

- I'm not satisfied with the back but it is mostly covered by the rudder (it is mapped just right of the texture for the port side)
- I'm not sure how to fix the air intake in the front with the existing textures. Check this snapshot:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/684228/7438320/b67d3ae4-f062-11e4-98f1-7b44ebbb73db.png)

**Comment by gilbertohasnofb** [comment]
> We have textures for the left and right side, but not the front or the back.
> [...]
> I'm not sure how to fix the air intake in the front with the existing textures. 

I do not understand why this is happening, can you explain better to me how can I help solve this?

**Comment by gilbertohasnofb** [comment]
Has this been fixed? I really don't see any black parts any longer.

**Comment by gilbertohasnofb** [comment]
@Juanvvc can you confirm this has been solved so we can close this issue?

**Comment by Juanvvc** [comment]
No, the black triangles in the front are not yet solved. In the development list, developers are discussing about taking back the last modification in the ubershader. These modifications in the ubershader made our bug apparent, but it is still a bug that must be fixed.

I'll look into all bugs related to the .blend file these weekend, the weather is going to be too windy to be outside :)

**Comment by gilbertohasnofb** [comment]
Ok Juan, just checking.

**Comment by onox** [comment]
@Juanvvc @gilbertohasnofb Is this bug still present?

**Comment by gilbertohasnofb** [comment]
I never saw this bug anyway, but @Juanvvc does and I don't think it's fixed yet.

**Comment by gilbertohasnofb** [comment]
Maybe should also move this issue to the 3.8 release milestone, what do you think @onox? It doesn't seem to affect everyone (I can't see it, for instance) and we have only 2 days left for our release milestone.

**Comment by onox** [comment]
@Juanvvc Can you still reproduce this? What video card, driver, and OS do you have?

**Comment by wlbragg** [comment]
I just looked at this on my computer and I don't see any of the issues that used to be there.

**Comment by gilbertohasnofb** [comment]
@Juanvvc could you please confirm if you still see this issue or not, so that we could maybe close this?

**Comment by onox** [comment]
Closing due to lack of needed info.

**Comment by gilbertohasnofb** [comment]
> Closing due to lack of needed info.

Just made another test, cannot reproduce this either.
